# Generated by Django 2.0.8 on 2018-10-15 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181007_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profie_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
