# Generated by Django 2.0.8 on 2018-10-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_profie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profie_image',
            new_name='profile_image',
        ),
    ]
